# Generated by Django 3.2.6 on 2021-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_input_file',
            field=models.CharField(max_length=500),
        ),
    ]
