# Generated by Django 3.2.6 on 2021-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0003_alter_question_question_input_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_input_file',
            field=models.CharField(max_length=500),
        ),
    ]
